server:
  port: 8026
spring:
  datasource:
    generate-unique-name: false
    url: jdbc:h2:mem:pw25s
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none